### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by moore-bryan** [galczo5/gnome-dark-apps#1]
Great little app, but can't seem to get it to work for me... Any suggestions?
```
/usr/local/lib/node_modules/gnome-dark-apps/dark_apps.js:16
    if (windowIds.length) {
                  ^

TypeError: Cannot read properties of null (reading 'length')
    at getWindowIdsFromRaw (/usr/local/lib/node_modules/gnome-dark-apps/dark_apps.js:16:19)
    at processData (/usr/local/lib/node_modules/gnome-dark-apps/dark_apps.js:66:23)
    at Socket.<anonymous> (/usr/local/lib/node_modules/gnome-dark-apps/dark_apps.js:79:41)
    at Object.onceWrapper (node:events:640:26)
    at Socket.emit (node:events:532:35)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:285:11)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by galczo5** [comment]
Can you send me information about node and distro that you are using? 
You can run it locally from the sources just download the sources and from the directory run `node ./dark_apps.js`. It looks like there's a problem in `getWindowIdsFromRaw` function.

You can try to modify code to:
```
    if (windowIds && windowIds.length) {
        return windowIds;
    }
```

But I think that the problem is in data from the os. I didn't test it on Wayland.

**Comment by moore-bryan** [comment]
Sure... I'm running Fedora 36 with kernel 5.19.4, GNOME 42.4, and Wayland on my Asus Zenbook UX425IA. 

Adding `windowIds &&` before `windowIds.length` seems to solve the issue...

Thank you for your help and your work on this clever little "app!"

**Comment by galczo5** [comment]
I'm actually surprised that it's working with Wayland. I'll try to add this condition and push the new version to npm.

**Comment by moore-bryan** [comment]
Just to check back in... The success with this is inconsistent. For example, I have it run at startup and upon launching Slack, for which I'm using this, it works as expected; however, if I *close* Slack and reopen it, it fails to do anything.

Not sure where to troubleshoot that one!

**Comment by darthcabs** [comment]
Any luck getting WM_CLASS (appId on Wayland) through JavaScript? GNOME now has a feature called Looking Glass that shows the wmclass, but I can't find a simple command line that would retrieve it

https://askubuntu.com/questions/981553/how-can-i-get-the-wayland-application-id-wm-class-equivalent-for-a-running-app
